server:
  port: 8081

system:
  hostname: localhost

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_auth
    password: Alexa1401* 
    username: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      # update: Crea las tablas si no existen, o las actualiza si cambia algo
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
    swagger-ui:
        operations-sorter: method
        default-model-expand-depth: 5
        default-model-rendering: model
    packagesToScan: com.unam.dwb.auth.controller
    pathsToMatch: /**
    
# Registry-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Admin-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,heapdump
  endpoint:
    health:
      show-details: always