# Gateway-service:
server:
  port: 8090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para AUTH
        - id: auth-service
          uri: lb://auth-service 
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        # Ruta para PRODUCT
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        # Ruta para INVOICE (y cart)
        - id: invoice
          uri: lb://invoice-service
          predicates:
            - Path=/invoice-service/**
          filters:
            - StripPrefix=1
        
        # Ruta para CUSTOMER
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Admin-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,heapdump
  endpoint:
    health:
      show-details: always