# Gateway-service:
server:
  port: 8090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          routes:
            # Ruta para AUTH
            - id: auth
              uri: lb://auth # lb = Load Balancer (usa el nombre en Eureka)
              predicates:
                - Path=/auth/** # Si la URL empieza con /auth...
              filters:
                - StripPrefix=1 # Quita "/auth" y manda el resto

            # Ruta para PRODUCT
            - id: product
              uri: lb://product
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1

            # Ruta para INVOICE
            - id: invoice
              uri: lb://invoice
              predicates:
                - Path=/invoice/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true